align.preset = "more"
# For fold-reformatting
newlines.source = fold
rewrite.imports.expand = false
rewrite.redundantBraces.ifElseExpressions = yes
rewrite.rules = [Imports, PreferCurlyFors, RedundantBraces, RedundantParens, SortModifiers]
rewrite.sortModifiers.order = [final, sealed, abstract, override, implicit, private, protected, lazy]
rewrite.trailingCommas.style = "always"
runner.dialect = scala3
version = "3.7.12"
